### ISSUE TITLE
Coinbase QR code is not recognized.

### ISSUE THREAD

**Issue by nuttycom** [adityapk00/zecwallet-lite#100]
**Describe the bug**
When attempting to deposit to Coinbase, the QR code that they render has the format `zcash:<taddr>`. This is not a valid ZIP 321 URI (as it is lacking an amount) but I guess that this is a special case that should be supported. I'll be opening a ticket to add this exception to ZIP 321.

**To Reproduce**
1. Scan a QR code of the form `zcash:<taddr>`

**Expected behavior**
The QR code is interpreted in the same fashion as if the user had scanned a bare T-address.

**Comment by adityapk00** [comment]
Fixed in 1892b49b7c00af5d1afd57b0df6e9b7d8aafe949
