### ISSUE TITLE
Cannot send memos

### ISSUE THREAD

**Issue by matemat13** [adityapk00/zecwallet-lite#105]
I have downloaded Zecwallet Lite from the Google Store and I have version v1.6.3.

**Describe the bug**
It is stated several times in the wallet's description that the Zecwallet Lite supports sending and receiving memos, but I didn't find a way to do this. There doesn't seem to be any field anywhere to fill-out a memo when sending Zcash nor is there any "memo" field in the received transactions. Maybe I'm just blind or misunderstand how the memos work, but I've been trying to figure this out for quite some time now.

**To Reproduce**
1. Download the application from Google Store.
2. Run it.
3. Try to find a field to include a memo when sending Zcash.
4. Fail.

**Expected behavior**
I expected there to be an input field to include a memo when sending Zcash to another account and a text field with the received memo when receiving Zcash.

**Desktop (please complete the following information):**
 - OS: Android 10
 - Browser: N/A
 - Version: Zecwallet Lite v1.6.3

**Additional context**
none

**Comment by adityapk00** [comment]
Note that memos can only be sent to z-addresses (addresses that start with `zs`). It seems like you are sending a transaction to a t-address (starts with `t`). 

The protocol doesn't allow sending memos to t-addresses, so the wallet hides the memo field, unless you send to a z-address

**Comment by matemat13** [comment]
Makes sense, thanks for the fast reply. Maybe mentioning this in the readme could save some time for future users (although I understand that it's a property of the protocol and not the wallet, so the user should ideally already know this unlike me :)).
