### ISSUE TITLE
Wallet.dat corrupted during transfer..

### ISSUE THREAD

**Issue by nankuse8** [adityapk00/zecwallet-lite#111]
Hi,
While actively using Zec wallet and sending/receiving transfers, I saw that the last 1-2 transfers were not happening. I tried again and again, I got a successful notification, but the balance did not decrease and no tx appeared. I turned it off and on again, but this time the password error started. My password is absolutely correct. I had already made transfers before the error. There is no other backup of my wallet.dat file. I can't find my keys.

Error
Could not unlock the wallet with the password.

debug.log
`
2021-06-27T02:16:54.591739200+03:00 ERROR::Error fetching latest price: grpc-status: Unimplemented, grpc-message: “unknown method GetCurrentZECPrice for service cash.z.wallet.sdk.rpc.CompactTxStreamer”
`

I want to repair my wallet.dat file.

 - Windows 10
 - Version 1.4.1 (during trouble)
    currently 1.6.3

**Comment by adityapk00** [comment]
Sorry you're having this issue. Zecwallet is fully non-custodial, which means unless you have saved the backup of one of (1) Seed phrase (2) wallet.dat or (3) Individual private keys, you won't be able to recover the wallet. 

Sorry.

**Comment by nankuse8** [comment]
> Sorry you're having this issue. Zecwallet is fully non-custodial, which means unless you have saved the backup of one of (1) Seed phrase (2) wallet.dat or (3) Individual private keys, you won't be able to recover the wallet.
> 
> Sorry.

I can see the current balance in my account. When I enter the password, I get the error "Could not unlock the wallet with the password". is there any way to fix it?

**Comment by adityapk00** [comment]
When you 'lock' the wallet, it encrypts all the spending keys. So you'll be able to see the balance, but not spend it. 

Unless you have one of (1) Seed phrase (2) wallet.dat or (3) Individual private keys, you won't be able to get hold of the spending keys.

**Comment by nankuse8** [comment]
I have wallet.dat which corrupts itself.. Is it not possible to repair?
