### ISSUE TITLE
Error after upgrading to 1.7.0

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#112]
Steps:
Upgrade to 1.7.0

What happened:
<img width="1412" alt="Screen Shot 2021-07-01 at 14 48 05" src="https://user-images.githubusercontent.com/227442/124120419-72b20000-da7c-11eb-904e-dd69b6d575af.png">

Expected result:
Wallet syncs from where it left off last time.

Notes:
Restore from seed worked afterwards.

**Comment by adityapk00** [comment]
Thanks for reporting this! Did you upgrade from 1.6.3? Did you use any of the previous BlazeSync betas?

I suspect there is a particular transaction with a certain type of memo that is confusing the wallet. Any ideas what that might be?

**Comment by rex4539** [comment]
Upgraded from 1.6.3 without ever running any BlazeSync betas.

**Comment by adityapk00** [comment]
Thank you for reporting this! I found and fixed it, will be available in 1.7.1 shortly.
