### ISSUE TITLE
Proper error message when attempting to encrypt twice

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#13]
Reproducibility: always

Steps:
1. Encrypt wallet
2. Encrypt wallet again.

What happened:

<img width="532" alt="Screenshot 2019-10-31 at 13 47 34" src="https://user-images.githubusercontent.com/227442/67944452-2b0f0d00-fbe5-11e9-9336-46b12e7beb9c.png">

Expected result:

Error message in human readable form.

**Comment by adityapk00** [comment]
Fixed in 58c80aaf819acc0ccc06fc611cf826d9a4ac9335
