### ISSUE TITLE
Where to download APK?

### ISSUE THREAD

**Issue by xcelente** [adityapk00/zecwallet-lite#141]
Can't find where to download the APK, apart from third party APK providers.

**Comment by prusnak** [comment]
+1 for publishing an APK on the release page here: https://github.com/adityapk00/zecwallet-lite/releases

+10 for getting ZecWallet Lite into https://f-droid.org/ 😄

**Comment by adityapk00** [comment]
APK is available here: https://github.com/zecwalletco/zecwallet-mobile/releases
