### ISSUE TITLE
Certificate Expired (second hand)

### ISSUE THREAD

**Issue by nathan-at-least** [adityapk00/zecwallet-lite#147]
Please make sure you have the latest ZecWallet. 

**Describe the bug**

I received a request for help from a user who showed a screenshot of ZWL desktop on Mac with a connection error for an expired certificate.

**To Reproduce**
1. I have not reproduced the behavior locally, but I assume the steps would be to run ZWL desktop and see the error. I'm not sure which backend service was involved (lightwalletd or something else), nor the relevant URL.

**Expected behavior**
The connection error should not appear.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser - unknown
 - Version - ???

**Additional context**
This is a second-hand report with a screenshot, so I haven't been able to verify locally if I can also see an expired certificate. It is possible that is could be specific to the user, perhaps, if they are using an old OS, but I'm speculating.

**Comment by adityapk00** [comment]
The user seems to be using an older version of Zecwallet Lite, which was connecting to the old server. 

The user needs to update their Zecwallet Lite desktop to the latest version (1.7.8) - https://github.com/adityapk00/zecwallet-lite/releases

(The correct LightwalletD server is https://lwdv3.zecwallet.co, which has the correct cert)
