### ISSUE TITLE
ZEC lite wallet wont load on any server

### ISSUE THREAD

**Issue by rememberme0417** [adityapk00/zecwallet-lite#148]
Everything was working fine yesterday and for months in the past but now I keep getting this error.  Have I been hacked?  It wont take my seed phrase either.  

![image](https://user-images.githubusercontent.com/103135420/162022949-4462d7c0-b13e-494b-8c6c-b364dfa7ba94.png)

**Comment by sibnia** [comment]
You are not alone in this situation, I am in the same situation. We need help @adityapk00

**Comment by adityapk00** [comment]
We had some issues with SSL certificates earlier. If you update your wallet to the latest and restart it, it should all work now.
