### ISSUE TITLE
Wrong bug reporting page

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#16]
Reproducibility: always

Steps:
Help -> File a bug

What happened:
https://github.com/zcashfoundation/zecwallet/issues/new is opened.

Expected result:
https://github.com/adityapk00/zecwallet-lite/issues/new is opened.

**Comment by adityapk00** [comment]
Fixed in 0d5ea2f5a511567e7f527b8cd7b17cce2804ffaa
