### ISSUE TITLE
T-Z transactions disseapear in the original wallet but can be imported into another wallet.

### ISSUE THREAD

**Issue by jordyvanraalte** [adityapk00/zecwallet-lite#163]
Please make sure you have the latest ZecWallet. 

**Describe the bug**
After experimenting with Zecwallet lite the last few weeks for our study, we noticed that some transactions were missing namely the T-Z transaction in our main wallet. After importing the viewing key, seed phrase or private key into a new wallet, these transactions reappear, however in the original wallet they are not there. It seems like this is a bug.

 

**To Reproduce**
Steps to reproduce the behaviour:
1. Do some transactions including T-Z transactions
2. Restart the wallet.
3. T-Z transactions disappeared.

**Expected behavior**
In the original wallet all the transaction done from that wallet should be visible.

**Desktop (please complete the following information):**
 - OS: Macbook Pro 2019 16” macOS Monterey 12.3 / Kali Linx 2022.2

**Additional context**

**Comment by adityapk00** [comment]
This is fixed in v1.7.13

**Comment by TracyHesiCecil** [comment]
not fix. My version is Zecwallet Lite v1.7.13
