### ISSUE TITLE
Error Sending Transaction

### ISSUE THREAD

**Issue by 1stDude** [adityapk00/zecwallet-lite#164]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>
Hello,

I'm trying to send Zcash to another wallet and keep getting the following error:
Error Sending Transaction
Error: SendResponse { error_code: -26, error_message: "16: bad-txns-sapling-spend-description-invalid" }

Can someone provide some insight or help? I've tried numerous times shielded and unshielded.

Thank you,
Gerry

**Comment by zahooha** [comment]
same problem
