### ISSUE TITLE
wallet problem

### ISSUE THREAD

**Issue by zahooha** [adityapk00/zecwallet-lite#165]
I have 2 wallets, I somehow figured out the first one, but I can’t do it with the 2nd one, the problem is this: funds are available only on transparent addresses, the balance is visible on a private address, but not available, funds transferred on 1.06.22 to a transparent one are also not available address (the amount and confirmation are visible in the block browser) but not in the wallet, I did everything that is indicated here, nothing helped.The problems started a week ago, so far everything has been fine.

**Comment by zahooha** [comment]
I did a rescan and sent it from another wallet to a new shielded address, nothing helped, the coins just disappeared

**Comment by zahooha** [comment]
> 
Windows 10 system and Windows 10 virtual machine

**Comment by adityapk00** [comment]
This is fixed in v1.7.13
