### ISSUE TITLE
Missing deposits since 1st June

### ISSUE THREAD

**Issue by timoconnellaus** [adityapk00/zecwallet-lite#169]
I mine ZEC using miners on F2POOL and since the 1st June transactions aren't arriving. I can see the transactions are confirmed

You can view my wallet here: https://blockchair.com/zcash/address/t1gAUmX4WdByhP5ucV6rUpRA86c3DQasa72

Additionally, using ZEC Wallet Lite on iPhone I can't send coins. I get the following error: "Error sending Tx. Error: SendResponse {error_code: -26, errror_message: "tx-expiring-soon: expiryheight is 1419220 but should be at least 1693154 to avoid transaction expiring soon" }

**Comment by jonson9** [comment]
Yes, this is due to NU5 network update.
I finally solved this problem after 3 days of trying

**Comment by jonson9** [comment]
Write me on t8well@protonmail.com I will help recover balance

**Comment by timoconnellaus** [comment]
Done

**Comment by timoconnellaus** [comment]
This guy is phishing

**Comment by jonson9** [comment]
I am not phishing :) if you don't want to provide details, it's you choice.

**Comment by timoconnellaus** [comment]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/3151605/172273097-660d9618-e859-43db-94eb-6c34424ee282.png">

Joined 2 days ago and not a contributor on the project. Asked for my private key or phrase in email

**Comment by jonson9** [comment]
Of course I asked, I'm not a magician to unlock the balance with the effort of thought :) 
I don’t know how well you understand this issue, but you asked the question, so you couldn’t manage it.
Yes, I joined recently and I am not a contributor on the project.

**Comment by TracyHesiCecil** [comment]
how to fix
