### ISSUE TITLE
Coredump when no .zcash folder is existent

### ISSUE THREAD

**Issue by DenioD** [adityapk00/zecwallet-lite#17]
Zecwallet Lightclient 1.0-beta1

Reproducibility: always

Steps:

    Delete your .zcash folder.
    Launch the client.
    Create a Wallet.

What happened:
Coredump without error Message.

Expected result:
Zecwallet should check for the .zcash folder and create one.

**Comment by adityapk00** [comment]
Thanks for finding this issue. Should be fixed now if you build from source. I'll make another beta release tomorrow for the compiled binaries

**Comment by DenioD** [comment]
Thanks for your excellent work!
