### ISSUE TITLE
Update Available dialog shows even when user is on the latest version

### ISSUE THREAD

**Issue by nighthawk24** [adityapk00/zecwallet-lite#18]
zecwallet-lite v1.0

The Update Available dialog shows on app start even when the user is on the latest version on macOS.

**To Reproduce**
1. Install zecwallet-lite v1.0
2. Open zecwallet-lite
3. See dialog

**Expected behavior**
The Update Available dialog should only show when the user is NOT on the latest version of zecwallet-lite..

**Desktop (please complete the following information):**
macOS 10.14.6

**Comment by adityapk00** [comment]
Fixed in 1.0.1
