### ISSUE TITLE
Improvement: Please add SOCKS 5 proxy support

### ISSUE THREAD

**Issue by gousasin** [adityapk00/zecwallet-lite#19]
Hello

I would like to suggest adding support for using a SOCKS 5 proxy. An option to enter a SOCKS 5 proxy IP and port in the settings/connections tab would be useful for some users.

Thanks

**Comment by rex4539** [comment]
This is actually a prerequisite for Tor support.

**Comment by adityapk00** [comment]
Duplicate of #26

**Comment by BenDover6969** [comment]
Why was this closed? Is there a way to use Zecwallet Lite with Tor?
