### ISSUE TITLE
GitHub tag version inconsistent

### ISSUE THREAD

**Issue by neutric** [adityapk00/zecwallet-lite#192]
Please make sure you have the latest ZecWallet. 

**Describe the bug**
GitHub tag version jumped from `v1.7.14` to `v1.17.15` and continues on `v.1.17.x` whereas files refer to the version as `1.7.x`.

**To Reproduce**
1. Go to https://github.com/adityapk00/zecwallet-lite/tags

**Expected behavior**
Consistent versioning.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 102

**Additional context**
Discovered while trying to bring the Homebrew Cask for ZecWallet up to the latest version.

**Comment by AArnott** [comment]
I noticed this too. The release names are still 1.7.x, but the tag names are 1.17.x.

**Comment by adityapk00** [comment]
Oops, sorry. Bug in my release script. 

Will be fixed with the next release.
