### ISSUE TITLE
How to create a new wallet/delete wallet OS files?

### ISSUE THREAD

**Issue by 7-of-9** [adityapk00/zecwallet-lite#195]
Sweet wallet!

Per subject: how can I make a new wallet, and/or delete old/unused wallet files from disk?

Can't see the paths anywhere. Would be good to have it on the Wallet menu, or in About?

**Comment by 7-of-9** [comment]
I'm running on MacOS... I want to create a new wallet - how do I do this? Delete/reinstall into Applications doesn't work - it picks up the old wallet. I've set a bad password on the current wallet, and need to nuke it and make a new one from the same seed. How?!

**Comment by adityapk00** [comment]
On MacOS, the wallet file is `macOS: ~/Library/Application Support/Zcash/zecwallet-light-wallet.dat`. Deleting this file will delete the wallet. Please make sure you have a backup/have the seed phrase before.
