### ISSUE TITLE
Error message sending from Sapling address to Orchard address

### ISSUE THREAD

**Issue by yoditar** [adityapk00/zecwallet-lite#196]
Hi @adityapk00!

I receive a **message error** when I want to send from **Sapling address to Orchard address**. You can see the following screenshot.

Thank you!

![signal-2022-08-17-105624_002](https://user-images.githubusercontent.com/74575326/185191115-37bb5d29-de3e-4803-8f94-984c6084cd24.png)

**Comment by adityapk00** [comment]
Thanks for letting me know. Does this still happen if you rescan?

**Comment by BostonZcash** [comment]
I'm receiving this same error message as well, when attempting to send Orchard > zs1. Will attempt rescanning.

**Comment by yoditar** [comment]
I will rescan the wallet and let you know if there are any changes. Thank you!

**Comment by BostonZcash** [comment]
@adityapk00 I've both rescanned the wallet on v1.8.3 and upgraded to v1.8.4 (pulled the .deb from the CI pipeline), however, I'm still running into the same error message. I now have funds on both a zs1 and u1 address. This message is happening (on v1.8.4) when attempting to send either to an external zs1 address, or the full balance (across Sapling + Orchard) to my u1 address.

**Comment by yoditar** [comment]
@adityapk00 In my case the rescan did not work. I keep getting the same error message.

**Comment by adityapk00** [comment]
Thanks to both of you. Unfortuntately, I'm still having trouble reproducing this, so can you please answer these questions to see if I can narrow it down:

1. Did you use the Orchard betas?
2. Is zecwallet lite continuously open or are you opening and saving it?
3. Are sapling -> sapling txns working? If you send ZEC 0.00001 to your own sapling address, does that work?
4. Are orchard -> t address txns working? If you send ZEC 0.00001 to your own transparent address, does that work?

Anything else you can let me know about what txns you can recall sending that got that wallet into this state will be incredibly helpful to me!

**Comment by yoditar** [comment]
1. No. I use this version: [v.1.8.3](https://github.com/adityapk00/zecwallet-lite/releases/tag/v1.8.3)
2. I am opening and saving it
3. Yes, sapling -> sapling txns working
4. I have no balance in Orchard

**Comment by jswihart** [comment]
I'm getting the same error. First time install of ZecWallet lite v. 1.8.4 on MacOS
Sent 1 ZEC to a taddr in the wallet. Trying to send that ZEC to a UA.

**Comment by adityapk00** [comment]
Are you trying to send to your own UA or to an external UA?

**Comment by adityapk00** [comment]
I'm having a hard time reproducing this still, so if any one of you is using a test wallet or wallet with very little funds, would you be willing to share the `zecwallet-light-wallet.dat` file with me so I can get to the bottom of this?

**Comment by adityapk00** [comment]
I think I was able to find and fix this issue. It was a rare combination of a reorg that happened at the exact right time.

Anyway, to fix this:
- Please download v1.8.5
- Do a rescan

This should (hopefully) fix all issues and get everything working again. If it doesn't please reopen this issue.
