### ISSUE TITLE
v1.8.5 stuck on block 419199 and rescan does not work

### ISSUE THREAD

**Issue by sandakersmann** [adityapk00/zecwallet-lite#197]
Running Zecwallet Lite v1.8.5 appimage on Ubuntu 22.04.1 LTS. It is stuck on block 419199 and rescan does not work.

![Screenshot from 2022-08-22 18-29-57](https://user-images.githubusercontent.com/6118832/185972883-9736c42d-d8cb-4408-b532-3e990b627872.png)

**Comment by adityapk00** [comment]
Is this a new wallet or did you upgrade to v1.8.5 and now it's not working?

**Comment by sandakersmann** [comment]
I imported a old seed in v1.8.5. Earlier versions did not work either.

**Comment by BostonZcash** [comment]
Same behaviour here. Had funds on both an Orchard and Sapling address on v1.8.3. Was running into https://github.com/adityapk00/zecwallet-lite/issues/196 and upgraded to v1.8.5. Initiated a rescan, but Zecwallet Lite believes block 419199 to be the latest. Attempting a new rescan, it shows 'Syncing batch 0 of 139' briefly, then returns to the Dashboard (showing no balances).

**Comment by adityapk00** [comment]
This is now fixed in v1.8.6

The problem was if your wallet's birthday was set to 0 or pre-sapling. 

Please reopen if it doesn't still work.

**Comment by sandakersmann** [comment]
Works like a charm now :)
