### ISSUE TITLE
Modified wallet settings not reflected until after restart (v1.8.8)

### ISSUE THREAD

**Issue by BostonZcash** [adityapk00/zecwallet-lite#199]
Installed the v1.8.8 .deb from the assets of the CD build.

Going to the new Wallet Settings, I choose 'Don't scan spammy transactions' and click save. Opening up the wallet settings again, I find the setting to have reverted to 'Scan all transactions'.

I choose the 'don't scan' option once more, save, and find it to have reverted again upon opening Wallet Settings a third time.

If the wallet application is closed and then reopened, then the intended new setting is now reflected (cannot determine yet if it's respected).

**Comment by adityapk00** [comment]
Unfortunately, because of the way the sync works, the setting won't be used until the *next sync*. So if you switch the setting in the middle of a sync, it will appear to have reverted. 

I'll fix this in the UI though.
