### ISSUE TITLE
WALLET INTERFACE IS NOT DISPLAYED

### ISSUE THREAD

**Issue by longnahimoquont** [adityapk00/zecwallet-lite#206]
Good afternoon, I have windows 11 arm when I run Zecwallet.Lite-1.8.8-win
my wallet starts up but the background is dark as in the screenshot

<img width="1338" alt="1" src="https://user-images.githubusercontent.com/114745857/193270621-8fb84d60-495e-4985-96c9-e0fa7fd2fb87.png">

**Comment by longnahimoquont** [comment]
what are the solutions to the problem ???

**Comment by adityapk00** [comment]
Windows on ARM is not supported. Please use the Zecwallet Lite CLI

**Comment by longnahimoquont** [comment]
I don't understand anything, please explain in more detail

**Comment by longnahimoquont** [comment]
most programs on arm 64 are simply emulated as x86 and x64

**Comment by longnahimoquont** [comment]
I just thought that Zecwallet.Lite-1.8.8-win would also work, but for some reason the interface does not
