### ISSUE TITLE
cannot send transactions from my zecwallet lite

### ISSUE THREAD

**Issue by jaschahal99** [adityapk00/zecwallet-lite#208]
Please make sure you have the latest ZecWallet. 

**Describe the bug**

i cannot send zec to t or z addresses. i get the following message:

Error: SendResponse { error_code: -26, error_message: "16: old-consensus-branch-id (Expected c2d6d0b4, found e9ff75a6)" }

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows laptop. windows 10 pro: Version	10.0.19043 Build 19043

**Additional context**

**Comment by adityapk00** [comment]
It looks like you are not using the latest Zecwallet. Please upgrade your Zecwallet Lite.

**Comment by jaschahal99** [comment]
thx. i have switched to android. better experience.
