### ISSUE TITLE
Error: Couldn't get network from server, connection refused. Is the server address correct?

### ISSUE THREAD

**Issue by spottyz** [adityapk00/zecwallet-lite#240]
Latest version of Zecwallet Lite and the following error message appears "Error: Couldn't get network from server, connection refused. Is the server address correct?". Will not allow me to restore a key phrase or create a new one. Any help greatly apprecatied.

**Comment by rtc311** [comment]
I am also having the same issue with Zecwallet lite on iOS. 

”Error Reading Wallet
Error: Couldn't get network from server, connection refused. Is the server address correct?”
 I have no options after tapping ok to the error message.

**Comment by rtc311** [comment]
Wallet is back and operational. I think I may be finding another wallet option.

**Comment by dspearson** [comment]
This project looks pretty much dead. There has been a long-standing bug (https://github.com/adityapk00/zecwallet-lite/issues/67 / https://github.com/adityapk00/zecwallet-lite/issues/149) which means that server selection does not work. There appear to be intermittent name resolution failures occurring, preventing the fetching of blocks (and the wallet appearing to hang, or sat doing nothing, when it is actually disconnected.)

Effective workaround is to add the following line to /etc/hosts for the duration of execution: `136.243.144.73 lwdv3.zecwallet.co`

It seems to be progressing for me when I do that, pointing to DNS being the issue.

**Comment by garfipokert1** [comment]
Hi, my wallet doesn't work. When will it be repaired? How do I recover my coins?




> Effective workaround is to add the following line to /etc/hosts for the duration of execution: `136.243.144.73 lwdv3.zecwallet.co`

It's not working

[<a href="https://ibb.co/FVfXT93"><img src="https://i.ibb.co/Dp6Y2NW/Screenshot-2023-08-26-11-57-13-674-edit-com-zecwalletmobile.jpg" alt="Screenshot-2023-08-26-11-57-13-674-edit-com-zecwalletmobile" border="0"></a>](url)

**Comment by pfarook** [comment]
I am facing the same issue and is there any way to transfer my ZEC from it?

**Comment by rtc311** [comment]
I was lucky enough to have the wallet reload a day or so later. When that happened I started to send funds back to the coinbase exchange. The wallet did not perform well and needed to be rescanned multiple times over about 4 days. It took about 4-6hrs per rescan, and my Zecwallet app had to stay open,on screen the whole time (without locking)  to scan successfully. Lucky to be off that wallet now. good luck, definitely get off that wallet asap I am currently using the zingolabs wallet and Y wallet.

**Comment by anhvuxyz** [comment]
Delete the zcash-lite file and download a new one. Worked for me

**Comment by tonyping** [comment]
I can't even find the iOS app on the App Store anymore, it's very disappointing when projects end like this.

**Comment by agentmic487** [comment]
@pfarook @spottyz  Are you still having this issues or got them solved?

**Comment by xalspaero** [comment]
@agentmic487 still having issues.  I recently installed ZEC wallet lite on a macbook and was unable to restore a wallet due to timeout error.  I haven't been able to load the app on iOS for a couple weeks now.  I would be willing to uninstall/reinstall/restore, or delete app data and try again, if the issue is fixed.

**Comment by rtc311** [comment]
I dunno man, dont delete it off your phone bc it looks like its unavailable on the Apple Store. Zecwalletlite Is no longer there…..  I feel bad for everyone still trying to retrieve Zec right now.

**Comment by xalspaero** [comment]
what is another wallet that the seed can be imported into?  I still have that obviously.

**Comment by spottyz** [comment]
Hey I found an alternative that works. Use/set up YWallet, then when in the app go to the three dots (top right), then go to advanced and tap on "sweep". You will then need to manually copy/paste your private key and wait for one confirmation. Note it wont appear in your wallets funds but if you tap on send it will be available. You can then send to what ever wallet/exchange you please. There's a link to Ywallet on the official z.cash website so you know it's legit etc.

Failing Ywallet there's always the option to download a full node but it's fairly technical and time consuming to do. But it is a possibility so don't give up hope if Ywallet ever stops working and you wander aimlessly onto this post. 

> what is another wallet that the seed can be imported into? I still have that obviously.

**Comment by zewallter3** [comment]
Hi guys. Tell me how to restore coins if I only have a seed phrase from the wallet, consisting of 24 words?

**Comment by Smith-303** [comment]
Hi. Look here, I think it will help you recover your coins. https://thienmaonline.vn/restoring-your-wallet-on-dogecoin-core-using-seedphrase-mnemonic-or-private-key-dogecoindev-1652196685

> Hi guys. Tell me how to restore coins if I only have a seed phrase from the wallet, consisting of 24 words?
