### ISSUE TITLE
Character input not visible when using dark theme

### ISSUE THREAD

**Issue by iwearahoodie** [adityapk00/zecwallet-lite#28]
![Screen Shot 2019-12-06 at 10 30 45 pm](https://user-images.githubusercontent.com/58599201/70330361-618d1700-1878-11ea-83ab-d4f9496e960a.png)

Characters are same colour as text box on macos, making characters not visible, when using dark theme.

**Comment by rex4539** [comment]
This is fixed in the latest build.
