### ISSUE TITLE
Provide a flatpak package on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [adityapk00/zecwallet-lite#31]
Hi. 1st of all, we have to say thank you for your efforts to create this wallet.
Do you thinking about making this wallet available as flatpak package on FlatHub ?
By making this wallet available as flatpak on FlatHub, you will make it available for almost all Linux users with minimum efforts from your side regarding packaging.

**Comment by adityapk00** [comment]
I'm going to close this as won't fix, since Zecwallet Lite now provides an AppImage instead

**Comment by Nokia808** [comment]
@adityapk00 
I'm very sorry for that ! Flatpak is much better & more convenient than AppImage. It is, also, more secure than AppImage. 
Moreover, it is more easy to you from packaging point of view !
Look for this:

https://github.com/vergecurrency/verge/issues/1028 
https://github.com/flathub/flathub/pull/1420
https://github.com/flathub/org.vergecurrency.verge-qt
https://www.flathub.org/apps/details/org.vergecurrency.verge-qt

Also, please read this carefully:
https://github.com/junrrein/pdfslicer/issues/103

Regarding security & trust level of flatpak on FlatHub, look for these application on it:
https://www.flathub.org/apps/details/cc.retroshare.retroshare-gui
This is an official package by developer of retroshare himself .......
Read this discussion also:
https://discourse.flathub.org/t/security-for-crypto-currency-apps-pivx/298

And PIVX is in the way to be available on FlatHub as flatpak in future ........

I have nothing else to say more about this topic. I wish you will change your mind.
