### ISSUE TITLE
Unable to open wallet

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#36]
Since this morning, whenever I launch the app, I get the following message.

<img width="439" alt="Screen Shot 2020-02-13 at 07 48 38" src="https://user-images.githubusercontent.com/227442/74408564-71f3dc00-4e3d-11ea-876b-d44344ba4bf4.png">

**Comment by adityapk00** [comment]
OK, I'm stumped. Is it possible the wallet file got corrupted? Can you try moving your existing wallet file (`~/Library/Application Support/Zcash/zecwallet-lite-wallet.dat`) and restoring from seed?

If you don't have the seed, you can see if it is recoverable by running the CLI with `cargo run --release -- --recover`?

**Comment by rex4539** [comment]
I restored from seed.

Interesting how it got corrupted though. Pretty sure it's due to zecwallet-lite-electron.

**Comment by adityapk00** [comment]
i think I might have an idea why it is getting corrupted. Let me fix it , until then can you pause using Zecwallet lite electron.

**Comment by adityapk00** [comment]
This was fixed in https://github.com/adityapk00/zecwallet-lite-electron/commit/50d40a5858d2af8417a74b334d30923a4f1d57b6

**Comment by rex4539** [comment]
I confirm that this commit fixed the bug.
