### ISSUE TITLE
Cannot create or restore wallet when wallet already exists

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#4]
Zecwallet Lightclient 1.0-beta1 (Oct 28 2019)

Reproducibility: always

Steps:
1. Create a new wallet or restore from seed.
2. Quit the client.
3. Restart the client.
4. Try to create a new wallet or restore from seed.

What happened:
Error message that a wallet already exists.

<img width="728" alt="Screenshot 2019-10-28 at 10 33 41" src="https://user-images.githubusercontent.com/227442/67663688-bfbc0580-f96e-11e9-81dc-86c2b70c1193.png">

Expected result:
Previous wallet is cleared and new wallet is created/restored.

**Comment by adityapk00** [comment]
Fixed in dead02137eb9099a947fa80b3786f550c5b3478c
