### ISSUE TITLE
CRITICAL: This release has a MITM Vulnerability that allows anyone to intercept requests

### ISSUE THREAD

**Issue by s-rah** [adityapk00/zecwallet-lite#40]
The library is initialized with the dangerous flag set to true. This turns off tls cert verification. This makes MITMing the connection trivial.  

![Screenshot_20200306_193058](https://user-images.githubusercontent.com/106626/76136049-45695500-5fe2-11ea-91d0-a5ae88b3bfcf.png)
![Screenshot_20200306_193039](https://user-images.githubusercontent.com/106626/76136050-4601eb80-5fe2-11ea-82a3-3e317be12e51.png)

**Comment by adityapk00** [comment]
Ooh, oops.
