### ISSUE TITLE
Switch back to https://zcha.in because https://chain.so reports inaccurate information

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#5]
Zecwallet Lightclient 1.0-beta1 (Oct 28 2019)

Reproducibility: always

Steps:
Check a shielded transaction on https://chain.so

What happened:
Transaction is not reported as shielded.

https://chain.so/tx/ZEC/c31ffdca03e16e7320d2527f01ebc4940de3814ee770270722fe98a1f9e27a1d
https://zcha.in/transactions/c31ffdca03e16e7320d2527f01ebc4940de3814ee770270722fe98a1f9e27a1d

Expected result:
Transaction is reported as shielded.

Notes:
Switch block explorer back to https://zcha.in

**Comment by rex4539** [comment]
I understand the reason that Zecwallet switched to https://chain.so is that 
https://zcha.in does not show unconfirmed transactions.

I have pinged @ppratscher to enable showing unconfirmed transactions on https://zcha.in

**Comment by ppratscher** [comment]
We have re-enabled showing pending tx on zcha.in

**Comment by adityapk00** [comment]
Is there a testnet version of the explorer as well?
