### ISSUE TITLE
Add an option to choose from which address send fund

### ISSUE THREAD

**Issue by fabricemrchl** [adityapk00/zecwallet-lite#50]
Hi,
Currently in send panel, fund of all addresses is merged and user only need to care about destination address and amount. It's very great for user expérience.
It would be better to add an option somewhere to allow advanced users to select from which address fund is send.
This feature will permit to create multiple address and used it as multiple account.
Thanks

**Comment by adityapk00** [comment]
I've considered this option, and have decided not to add this feature to Zecwallet Lite. The Lite client will always prioritize ease-of-use, and selecting from addresses is quite complex. 

This feature is present in Zecwallet Fullnode (which allows you to select from addresses), so if you want power features, I'd recommend using the full node version.
