### ISSUE TITLE
'Error: failed to fill whole buffer' upon launch

### ISSUE THREAD

**Issue by BostonZcash** [adityapk00/zecwallet-lite#51]
**Describe the bug**
An instance of Zecwallet Lite using imported seed words which had previously run and transacted successfully, now fails to launch following an update (.deb) to the latest release (v1.1.7).

The timing of this error and the update may have been coincidental as it wasn't being consistently run before then, and other package upgrades had previously taken place.

After launch, wallet screen now always displays:

```
Error Initializing Lightclient
Error: failed to fill whole buffer
```

Running in the terminal produces:

```
$ zecwallet-lite
[5160:0426/194252.545757:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
(node:5163) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:5163) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
```

The `GL ERROR` is thrown again whenever clicking on the drop-down menus (File, Wallet, etc.)

**To Reproduce**
I have not yet attempted to reproduce beyond relaunching the application on the affected machine.

1. Import seed words of existing wallet into an instance of Zecwallet Lite below v1.1.7 on Ubuntu 20.04.
3. Use wallet with success.
3. After time or following an upgrade to v1.1.7, start wallet and be presented with the error.

**Expected behaviour**
No such error is thrown, wallet proceeds to the Dashboard.

**Desktop (please complete the following information):**
 - Ubuntu 20.04 LTS
- Kernel 5.6.7
- Zecwallet Lite ~v1.1.5 (success), v1.1.6 (success), v1.1.7 (affected version)

**Additional context**
I have Zecwallet FullNode on the same Linux system and running without issue.

This happens on the Lite wallet regardless of which liteclient server I choose. This is the only setting I can change, as the drop-down menu items are non-functional.

**Comment by adityapk00** [comment]
Hmm... I wonder if your wallet file is corrupted somehow. Can you :

1. Backup your (possibly corrupted) `zecwallet-light-wallet.dat` (It is in the `~/.zcash` folder)
2. delete `~/.zcash/zecwallet-light-wallet.dat`
3. Start zecwallet lite and restore from seed
4. See if zecwallet continues to work after closing + reopening

**Comment by BostonZcash** [comment]
@adityapk00 Thanks, I'll try that. I was also able to recreate on macOS.

I had previously imported the same seed words (no blockheight given) on Zecwallet Lite v1.1.2 on macOS 10.15.4.

Immediately upon finishing scanning for addresses, I received this message upon boot:

```
Error Initializing Lightclient
Error: failed to lookup address information: nodename nor servname provided, or not known
```

Never progressed past that. That was as recently as today, though I've now upgraded it to v1.1.7 as well, and then received the same as on Ubuntu:

```
Error Initializing Lightclient
Error: failed to fill whole buffer
```

**Comment by adityapk00** [comment]
I think there was a bug in an old version (IIRC 1.1.2) that wasn't rescanning properly. It was fixed in 1.1.4, I think. 

So if you import the seed into the latest zecwallet-lite (after deleting/moving your `zecwallet-light-wallet.dat` file), it should work. Please let me know if it doesn't, that would be a new bug!

**Comment by BostonZcash** [comment]
Upon moving the wallet out of the way and reimporting the seed words on Linux, syncing stalled at block 661200. Did not progress even after house. This struck me as familiar, as I recall the same stalled syncing previously on macOS.

Closing the application and restarting it then threw the `failed to fill whole buffer` error as before, without any further syncing attempted.

**Comment by adityapk00** [comment]
I'm unable to repro this with various combinations of importing and seed words. Can you DM me on twitter so I can try to get to the bottom of this?

**Comment by adityapk00** [comment]
Is there anything interesting in the `zecwallet-light-debug.log` ?

**Comment by BostonZcash** [comment]
Nothing that stands out to me in `zecwallet-light-wallet.debug.log`. Sent a message on Wire. :+1:

**Comment by adityapk00** [comment]
Fixed in https://github.com/adityapk00/zecwallet-light-cli/commit/703192f45bad6ba9347258e283b1a6469357477c

**Comment by cdcxzl** [comment]
Zecwallet.Lite-1.1.9-win

Error Initializing Lightclient
Error: failed to fill whole buffer

i have zecwallet-light-wallet.dat only. 
no seed..

what am i to do ?

**Comment by cdcxzl** [comment]
help me please..

**Comment by adityapk00** [comment]
@cdcxzl the error “failed to fill whole buffer” is indicative of wallet corruption on disk. The issue was fixed to recover these from the seed phrase. 

Unfortunately if you don’t have the seed phrase, there’s no reliable was to recover your wallet. You have two options. 

1. You can download the zecwallet-light-cli and try running it with the —recover option to see if it can recover your seed phrase 
https://github.com/adityapk00/zecwallet-light-cli

2. You can DM me on Twitter or discord and I can try to see if anything is salvageable from your wallet data file. I’m @zecwallet on Twitter.

**Comment by protongirl** [comment]
Ohh I have the same problem! no seed but money... and Error

**Comment by protongirl** [comment]
> 
> 
> @cdcxzl the error “failed to fill whole buffer” is indicative of wallet corruption on disk. The issue was fixed to recover these from the seed phrase.
> 
> Unfortunately if you don’t have the seed phrase, there’s no reliable was to recover your wallet. You have two options.
> 
>     1. You can download the zecwallet-light-cli and try running it with the —recover option to see if it can recover your seed phrase
>        https://github.com/adityapk00/zecwallet-light-cli
> 
>     2. You can DM me on Twitter or discord and I can try to see if anything is salvageable from your wallet data file. I’m @zecwallet on Twitter.

please tell me your discord, I send you me zecwallet-light-wallet.dat and hope you can restore

**Comment by adityapk00** [comment]
@protongirl can you email me. aditya@zecwallet.co
