### ISSUE TITLE
Amount is not handled correctly if it's too small

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#52]
<img width="1017" alt="Screen Shot 2020-04-27 at 22 39 37" src="https://user-images.githubusercontent.com/227442/80414201-572bf200-88d9-11ea-9054-fbf929029664.png">
<img width="813" alt="Screen Shot 2020-04-27 at 22 40 09" src="https://user-images.githubusercontent.com/227442/80414212-5b580f80-88d9-11ea-8abf-66c87684f306.png">
<img width="1021" alt="Screen Shot 2020-04-27 at 22 40 39" src="https://user-images.githubusercontent.com/227442/80414217-5dba6980-88d9-11ea-8af0-95561f31c04b.png">
<img width="972" alt="Screen Shot 2020-04-27 at 22 40 57" src="https://user-images.githubusercontent.com/227442/80414223-5f842d00-88d9-11ea-9f7d-0526ec6d761e.png">

**Comment by rex4539** [comment]
It is now handled correctly in all other places except here.

<img width="969" alt="Screen Shot 2020-04-28 at 08 17 51" src="https://user-images.githubusercontent.com/227442/80449956-122fac00-8929-11ea-9956-ab3b7164079a.png">

**Comment by adityapk00** [comment]
Actually, that part is correct, since it includes the fee. So the tx has one sapling output of zec 0 plus fee of zec 0.0001
