### ISSUE TITLE
Missing addresses from recovered ZECWallet Lite

### ISSUE THREAD

**Issue by Onlooka** [adityapk00/zecwallet-lite#55]
I had the same problem that people were having with  "Failed to fill whole buffer"

I installed the patch.. which didn't work. Then I contacted aditypapk00 directly on twitter. 
Renamed the .dat file which allowed me to restore my ZECWallet Lite.

When I restored my wallet all my addresses which had the majority of my ZEC were gone. 
Today I divided up my ZEC to different addresses on my wallet and all those addresses were missing except for one which only had 1 ZEC inside..

This was my entire life savings.. Currently I'm rescanning/resyncing the blockchain to see if that's it.. but.. at this point. yeah.. everything that I had... I cant even think clearly right now..

**Comment by adityapk00** [comment]
The addresses are deterministic in Zecwallet Lite, so if your addresses are missing, you can simply create them again. On the "Receive" tab, simply click "New Shielded Address" or "New Transparent Address" until you get your addresses, then rescan. 

Your funds should be safe.

**Comment by adityapk00** [comment]
Also, make sure that you enter the correct wallet birthday when restoring. If you don't have your wallet birthday, enter "0" to rescan from the genesis block.

**Comment by Onlooka** [comment]
This still didn't work. Im unistalling and reinstalling so that i can sync my wallet birthday for a faster sync...

**Comment by adityapk00** [comment]
Did you create the new addresses?

**Comment by Onlooka** [comment]
Sorry i cant think straight right now, becuase i was panicking. I created the new addresses but didnt rescan. I'm just unistalling so i can choose the correct birthday instead of scanning from the genesis block.

**Comment by adityapk00** [comment]
I'm 99% sure your funds are safe. You need to create the addresses and then do the rescan.

I'm also fixing the issue in code in a new version of Zecwallet which I should release in the next few hours.

**Comment by Onlooka** [comment]
Ok, I can breathe easier now. I added 6 more addresses then rescanned from an approximate block height, and the funds are there now. Thank you!
