### ISSUE TITLE
ZecWallet failed to function properly

### ISSUE THREAD

**Issue by bolaigeafe** [adityapk00/zecwallet-lite#56]
![Screenshot_20200521-221053](https://user-images.githubusercontent.com/52111555/82766088-f3cbac00-9e13-11ea-9fe2-458e9f109fc1.png)

**Describe the bug**
ZecWallet failed to function on Android 8.1.1 and Window 7 PC.

**To Reproduce**

**Expected behavior**
I expect the ZecWallet to displayed shielded address when opened and respond to click on Receive and Send buttons, but it failed.
It further displayed an error message as you can see in the picture attached "no connection" on the screen, meanwhile there is full internet service on the devices.

**Desktop (please complete the following information):**
 - OS: Android
 - Browser [Chrome
 - Version 8.1.1

**Additional context**
None

**Comment by adityapk00** [comment]
This is the companion app. You need to connect it to a Zecwallet that is running on the desktop. 

The Zecwallet Android app that doesn't need the desktop node is coming this week!

**Comment by adityapk00** [comment]
If you want to use the Android app, please click the "Scan QR Code" on the android app, and go to "Wallet -> Connect Mobile App" on the desktop
