### ISSUE TITLE
Error Reading Wallet after fresh install

### ISSUE THREAD

**Issue by agnelvishal** [adityapk00/zecwallet-lite#57]
**Describe the bug**
This is the error I got. 
![Screenshot_2020-06-06-07-17-33-705_com zecwalletmobile](https://user-images.githubusercontent.com/10105332/83933456-461eac80-a7c6-11ea-8cf4-f61e11ded166.jpg)

**To Reproduce**
1. Download Zec Wallet lite from Google Play store. 
2. Open the app.

**Context**
The app I downloaded is in the latest version as per Google play store. I didn't test the direct apk. 

I have Android 9.

**Comment by adityapk00** [comment]
Thank you for this report. I need some help getting to the bottom of this. 

What phone model do you have?
Do you get the same error if you uninstall the app and install it again from the play store?

**Comment by agnelvishal** [comment]
I have redmi note 7s.
In play store, I am unable to find the app now.
Under the publisher zecwallet there is zecwallet companion app but no zecwallet lite.

**Comment by adityapk00** [comment]
Is the app not availble here: 
https://play.google.com/store/apps/details?id=com.zecwalletmobile

**Comment by agnelvishal** [comment]
The app is showing now. Previously it was not shown. Maybe because I had just uninstalled the app and searched for it and so it got hidden somehow. I don't know.

Anyways, I reinstalled the app and it works. Thanks.

However, import of account by private key is an essential feature for me which is already raised as a feature request.
