### ISSUE TITLE
Zec wallet not generating new address

### ISSUE THREAD

**Issue by okra99** [adityapk00/zecwallet-lite#58]
<!-- 
Zec light wallet in Linux not generating new address when button "Generate new address" was pushed, because wallet was encrypted with password. I cant understand why wallet doesnt ask password during opening? When I go to menu->Unlock and put the password then wallet generating news address, but if I will not do that then it will not say user, "Please unlock your wallet before generating new address" or something like that. I think the best if password would be asked after app start. it will solve all issues. 
--!>

**Comment by okra99** [comment]
Zec light wallet in Linux not generating new address when button "Generate new address" was pushed, because wallet was encrypted. I cant understand why wallet doesnt ask password during opening? When I go to menu->Unlock and put the password then wallet generating news address, but if I will not do that then it will not say user, "Please unlock your wallet before generating new address" or something like that. I think the best if password would be put when opening app. it will solve all issues.

**Comment by adityapk00** [comment]
Thanks for reporting this issue. Fix should be in the next release.
