### ISSUE TITLE
Funds missing when reinstalling app and restoring wallet 

### ISSUE THREAD

**Issue by cabrock1** [adityapk00/zecwallet-lite#60]
**Describe the bug**
Send tx were not going through (they would freeze on page saying "tx processing, this could take up to one minute", so I unistalled the app, reinstalled it, restored my wallet using mnemonic (phrase) and block bday, let sync blocks, and my funds havent shown up.

**To Reproduce**
1. Copy Mnemonic
2. Uninstall app
3. Reinstall app
4. Click "restore wallet"
5. Paste Mnemonic and enter block bday
6. Wait for blocks to sync
7. See balance

**Expected behavior**
The funds that were in the wallet originally should be there still upon restoring the wallet, but mine arent (about $25 worth, which is enough to matter to me right now).

**Desktop (please complete the following information):**
 - OS: Android

**Additional context**
If my funds were lost because of your app then I think it is only right that you replace them, after all it is just $25

**Comment by adityapk00** [comment]
Note that the funds are not held in the wallet, but in the seed phrase, so Zecwallet really doesn't have any control over them. Assuming you have the correct seed phrase and birthday I'd recommend you try this:

Install Zecwallet lite for your desktop and try to recover your seed phrase there. Please leave birthday as 0 so as to make sure to scan it from the start. 
2. If your phone is not syncing, you might try connecting to wifi (on your phone) to improve sync speed. 

You can also DM me on twitter (https://twitter.com/zecwallet) and I can help you recover your private funds from the seed.
