### ISSUE TITLE
Send tab doesn't explain why funds are not spendable

### ISSUE THREAD

**Issue by dcposch** [adityapk00/zecwallet-lite#62]
This is a new-user experience report.

**Describe the bug**

I sent myself ZEC. The transaction completed, I still have the same total amount as before, but the funds are no longer spendable.

I just installed Zecwallet Lite and used it for the first time. I find the distinction between "All Funds" and "Spendable Funds" insufficiently explained.

**To Reproduce**

1. Create a shielded address
1. Send ZEC from one of your transparent addresses to the new shielded address
1. Wait for the transaction to show up in the Transactions tab
1. Go to the Send tab
1. Note that the amount you sent is still present in All Funds but missing from Spendable Funds

There is no further explanation or ETA.

**Expected behavior**
If there is a difference between Spendable and All Funds, then the wallet should explain why and for how long.

Is there some minimum age, in blocks, that shielded funds have to be before you can spend them?

How many more blocks do I have to wait?

**Desktop (please complete the following information):**
 - macOS Catalina

**Comment by adityapk00** [comment]
Thank you for reporting this. 

I added a new tooltip to the page when funds are waiting for confirmations with additional info. Should be included in the next release.
