### ISSUE TITLE
Zecwalletlite doesn't work on Windows 8.1

### ISSUE THREAD

**Issue by OlScratch** [adityapk00/zecwallet-lite#64]
Please make sure you have the latest ZecWallet. 

Yes, 1.2.2

**Describe the bug**

The window is all black, and none of the menu items do anything except for the ones like "Report Bug" that open a web page. "Donate" didn't even do anything.

**To Reproduce**

1. Download 1.2.2 for Windows (I tried both MSI and Binaries.)
2. Run it.
3. Click "File -> Pay URI"

**Expected behavior**

I expected something to happen, but nothing happened. Same for all other menu commands.

**Desktop (please complete the following information):**

Windows 8.1

Firefox

8.1

**Additional context**

**Comment by OlScratch** [comment]
By the way, I installed Zecwalletfull and it is working normally.

**Comment by adityapk00** [comment]
Unfortunately, Win 8.1 is not supported. I don't have Windows 8.1 available to me to debug this issue, unfortunately. Sorry.
