### ISSUE TITLE
Connection error on startup

### ISSUE THREAD

**Issue by jkdev601** [adityapk00/zecwallet-lite#65]
ZecWallet Lite 1.1.12
Connection error on startup:

`Error Initializing Lightclient
Error: grpc-status: Unknown, grpc-message: "error requesting block: Post http://0.0.0.0:8232: dial tcp 0.0.0.0:8232: connect: connection refused"`

Same error after switching LightwalletD servers

**Comment by rex4539** [comment]
Looks like a backend issue. Also seeing the same.

This should be treated as a high priority issue. I'm assuming everybody using Zecwallet Lite or Zecwallet Mobile is locked out of their wallets.

**Comment by jkdev601** [comment]
Update:
ZcashFR (Community) - https://lightd-main.zcashfr.io:443 seems to be working now

**Comment by chairulakmal** [comment]
@jkdev601 I got the ZcashFR server working for me but someone reports ["timed out error" at zcash forum](https://forum.zcashcommunity.com/t/my-internet-is-working-however-i-am-getting-the-following-error-accessing-zecwallet-lite/37362/6)

Also I don't think you can currently change LightwalletD server on the mobile version (sorry if this is the wrong github repo for this)

**Comment by hganesan18** [comment]
> @jkdev601 I got the ZcashFR server working for me but someone reports ["timed out error" at zcash forum](https://forum.zcashcommunity.com/t/my-internet-is-working-however-i-am-getting-the-following-error-accessing-zecwallet-lite/37362/6)
> 
> Also I don't think you can currently change LightwalletD server on the mobile version (sorry if this is the wrong github repo for this)

The error I get when trying FR is as follows:

"Error Initializing Lightclient
Error: transport error: error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)"

**Comment by rex4539** [comment]
ZcashFR doesn't work for me either.

It's a very unfortunate coincidence because I think I read somewhere that Aditya is on vacation this week.

I hope he still checks emails/messages :)

**Comment by dmbaker12** [comment]
Getting the following error as well
![6D165759-0EEE-4E77-B541-769F843C50A1](https://user-images.githubusercontent.com/32279926/93343353-65ce6380-f7fe-11ea-8a24-d4fa90095170.jpeg)

**Comment by BostonZcash** [comment]
The Nighthawk infrastructure is up. Feel free to point your light wallet instances to shielded.nighthawkwallet.com:9067

**Comment by rex4539** [comment]
Thanks Neal but this still doesn't work for me.

<img width="1412" alt="Screen Shot 2020-09-16 at 16 55 24" src="https://user-images.githubusercontent.com/227442/93347223-7fdb6680-f83d-11ea-8577-1b692185afe9.png">

**Comment by jkdev601** [comment]
> Thanks Neal but this still doesn't work for me.
> 
> <img alt="Screen Shot 2020-09-16 at 16 55 24" width="1412" src="https://user-images.githubusercontent.com/227442/93347223-7fdb6680-f83d-11ea-8577-1b692185afe9.png">

Check for typos https://shielded.nighthawkwallet.com:9067 is working for me

**Comment by adityapk00** [comment]
Sorry everyone, there was an issue with AWS, which also took out my monitoring servers :(

All fixed now.
