### ISSUE TITLE
Import wallet from Linux zcash-cli

### ISSUE THREAD

**Issue by t0rbalan** [adityapk00/zecwallet-lite#70]
Please make sure you have the latest ZecWallet. 

**Describe the bug**
I want to import existing wallet.
I have the  z_listaddresses and the  r_listaddresses as well as the private keys.

zcash-cli z_exportwallet "waletbackupbckp" /media/ssd/waletbackup

**To Reproduce**
Open app - choose import existing wallet
It does not let you do it, unless you have a mnemonic phrase.
On zcash linux wallet this thing did not exist or i did not get asked for it ( i have no mnemonic phase)
I can use my wallet on linux fine

**Expected behavior**
I want to be able to open wallet without mnemonic phrase, but key + pass only.

**Desktop (please complete the following information):**
windows 10
edge

**Additional context**

**Comment by adityapk00** [comment]
You can import the individual private keys. 

1. Create a new wallet with zecwallet-lite (with a new passphrase)
2. Import the individual private keys using Edit -> Import Private key
