### ISSUE TITLE
How to restore backup from 2017

### ISSUE THREAD

**Issue by szymek9876** [adityapk00/zecwallet-lite#77]
Hi everyone. I have download zecwallet Lite. Trying to import PRIVATE KEY(not using since 2017) but it says "The input key was not recognized as either a sapling spending key or a sapling viewing key
"

I have private key and public key and Backup file - wallet.dat.

My old zcash wallet app doesn't open on my PC, don't know why

What can I do to restore it my Friends?
have a Good Day

**Comment by adityapk00** [comment]
What you have is a full node wallet, so you'll have to do the following:

1. Download Zecwallet full node - www.zecwallet.co/fullnode.html
2. Sync it fully - This can take days or even a week
3. Replace the wallet.dat that you have from your backup
4. Do `zcashd.exe -rescan`, which will take a few hours
5. Now, your funds will be visible in the Zecwallet Fullnode
