### ISSUE TITLE
Unconfirmed transactions are not shown after client restart

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#8]
Zecwallet Lightclient 1.0-beta1 (Oct 28 2019)

Reproducibility: always

Steps:
1. Send a transaction.
2. Quit the client.
3. Launch the client.

What happened:
The unconfirmed transaction is not shown and balance is wrong.

Expected result:
The unconfirmed transaction is shown and balance is correct.

**Comment by adityapk00** [comment]
This is unfortunately a limitation of the lightclient protocol. It doesn't get access to mempool transactions, so Zecwallet "remembers" stuff that it sent. When it restarts, the server doesn't respond with what's in the mempool, so it forgets.

**Comment by adityapk00** [comment]
Maybe I can store the unconfirmed transactions in the wallet file, so at least it will remember them on restart.

**Comment by adityapk00** [comment]
Fixed in the blazesync build
