### ISSUE TITLE
It's not possible to cut and paste OUT of the memo field

### ISSUE THREAD

**Issue by zancas** [adityapk00/zecwallet-lite#85]
An interesting use case is sending z2z transactions with a "return address" in the memo field.   Unfortunately the cut-and-paste functionality on my phone (which _DOES_ allow me to copy the address I have sent to, does _not_ allow me to copy the memo field contents).

For example:  I can copy the text that starts with:   `zs1...` but not the characters that start with:  `Also try:...`
![A2179B21-11B2-463A-B703-97F5546B4687-616-0000009BAFBC64AD](https://user-images.githubusercontent.com/640955/104136186-d838f580-5351-11eb-8c35-9a9ea5cc4e08.jpg)

**Comment by adityapk00** [comment]
Fixed in https://github.com/zecwalletco/zecwallet-mobile/commit/f49172fa6f65fa3dcc640e20c3a486471efcfb89
