### ISSUE TITLE
Compilation error on Linux, Arch, jubjub rust fails

### ISSUE THREAD

**Issue by GIJack** [adityapk00/zecwallet-lite#88]
Please make sure you have the latest ZecWallet. 

**Describe the bug**
when running
yarn install - works
yarn package-linux - fails with:
```

   Compiling jubjub v0.5.1
error[E0277]: cannot multiply-assign `<E as Engine>::Fr` by `&&<E as Engine>::Fr`
   --> /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/bellman-0.8.0/src/groth16/generator.rs:401:39
    |
401 |                         at.mul_assign(&beta);
    |                                       ^^^^^ no implementation for `<E as Engine>::Fr *= &&<E as Engine>::Fr`
    |
    = help: the trait `MulAssign<&&<E as Engine>::Fr>` is not implemented for `<E as Engine>::Fr`
help: consider further restricting the associated type
    |
331 |     ) where <E as Engine>::Fr: MulAssign<&&<E as Engine>::Fr> {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0277]: cannot multiply-assign `<E as Engine>::Fr` by `&&<E as Engine>::Fr`
   --> /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/bellman-0.8.0/src/groth16/generator.rs:402:39
    |
402 |                         bt.mul_assign(&alpha);
    |                                       ^^^^^^ no implementation for `<E as Engine>::Fr *= &&<E as Engine>::Fr`
    |
    = help: the trait `MulAssign<&&<E as Engine>::Fr>` is not implemented for `<E as Engine>::Fr`
help: consider further restricting the associated type
    |
331 |     ) where <E as Engine>::Fr: MulAssign<&&<E as Engine>::Fr> {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to `2` previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `bellman`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed


```

**Expected behavior**
yarn to finish compiling

**Desktop (please complete the following information):**
 - Linux BOXNAME 5.10.9.a-1-hardened #1 SMP PREEMPT Tue, 19 Jan 2021 19:46:30 +0000 x86_64 GNU/Linux
 - $ pacman -Q yarn
yarn 1.22.10-1
- $ pacman -Q rust
rust 1:1.49.0-1
- $ pacman -Q nodejs
nodejs 15.6.0-1
- $ pacman -Q npm
npm 6.14.11-1

 - zecwallet-lite 1.4.1, as linked from downloads page.

**Additional context**

**Comment by adityapk00** [comment]
I'm about 90% sure that this error is because of the Rust compiler version. I guess you're using rustc 1.49, and  I think the compilation doesn't work for that version. If you use rustc 1.48, I think it works. 

I'm not really sure why, but if you can confirm your rust compiler version, I might be able to dig into it.

**Comment by adityapk00** [comment]
Oh, I just noticed that your rust version is v1.49. I think this is the issue, but I don't know why yet. 

If you switch to 1.48, I think it will work.

**Comment by adityapk00** [comment]
Upstream issue: https://github.com/zcash/librustzcash/issues/333

**Comment by adityapk00** [comment]
This was fixed
