### ISSUE TITLE
Why does zecwallet-lite build require zcashd?

### ISSUE THREAD

**Issue by nathan-at-least** [adityapk00/zecwallet-lite#98]
**Describe the bug**

The README says:

> Zecwallet Lite is written in Electron/Javascript and can be build from source. Note that if you are compiling from source, you won't get the embedded zcashd by default. You can either run an external zcashd, or compile zcashd as well.

Are these docs wrong about `zecwallet-lite` requiring `zcashd`?

If not, why does `zecwallet-lite` require `zcashd`?

**To Reproduce**

Read https://github.com/adityapk00/zecwallet-lite#compiling-from-source

**Expected behavior**

`zecwallet-lite` (a light wallet) would not require `zcashd` (a full node) and the docs would be clear about that.

**Comment by adityapk00** [comment]
Sorry, this is a copy-paste error from Zecwallet Fullnode. 

Fixed now.
