### ISSUE TITLE
Question/error on fork of this project

### ISSUE THREAD

**Issue by interbiznw** [adityapk00/zecwallet-lite#99]
just curious if you had any idea, on a fork/zcash clone why we would be getting this error?

```Error: SendResponse { error_code: -26, error_message: "16: bad-txns-sapling-binding-signature-invalid" }```

![image](https://user-images.githubusercontent.com/16450422/112262955-b39faa80-8c2b-11eb-9ea6-63af2851072e.png)
![image](https://user-images.githubusercontent.com/16450422/112262994-c1553000-8c2b-11eb-9074-f961716fb7e8.png)

TIA for any help/guidance on where to look

**Comment by adityapk00** [comment]
Your fork most likely has a wrong or incorrect `consensusBranchId`. This is returned by the lightwallet server that you are connecting to.

**Comment by interbiznw** [comment]
> Your fork most likely has a wrong or incorrect `consensusBranchId`. This is returned by the lightwallet server that you are connecting to.

We have sapling activated and its using branch id 76b809bb same as zcash, and I am guessing the lightwalletd uses the same? Not seeing where the mismatch would be, but transactions work normally on the network its just issue with the transactions created by this litewallet/cli/librustzcash/lightwalletd combo



and just verified when lightwallet server starts it indeed returns the same results..so not seeing how its constructing the transaction wrong

```INFO[2021-03-25T09:41:13Z] Got sapling height 25 chain test branchID 76b809bb```



I thought I read somewhere that you are using your own librustzcash repo cause there were some changes you needed specifically to the lite wallet or something? Wondering if that could be an issue, but I believe I also later cloned your librustzcash repo and made some changes for the address prefixes there and think that was it. Oh and the block heights for the upgrades, aside from that we did not change any other parameters that I can think of that would need to be changed in librustzcash

Only other major thing we changed was the equihash parameters to 192,7 and new genesis mined with 192,7 as well... is there some other parameters that would need to change in librustzcash for a new chain if not much was even altered?

**Comment by adityapk00** [comment]
If you are sure that the branchID is correct, another possibility is that the blake2b hash personalization string is mismatched. 

You need to use the same personalization string that you're using in your zcashd fork in your librustzcash. Search the codebase for "personalization string"
